### PR TITLE
drakrun: rtf association

### LINKED ISSUE #397: Support for .rtf files
Word can already open those files, only need to add association for startup command.

### PR DESCRIPTION
**Pull request by techathena**
closes #397 

trying to implement a proposed solution
https://github.com/CERT-Polska/drakvuf-sandbox/issues/397#issuecomment-778634245

### CODE REVIEW

**Review by chivay — APPROVED** [review]
Could you rename the PR to something more adequate for merging (the title will become the commit message after squashing)?
We're trying to keep the convention: `[area of modifications]: [what was done]`
eg. `drakcore: Add foo and bar`

Apart from that LGTM :+1:

**Review by icedevml — APPROVED** [review]
Thanks for contribution. As above, please change the title of the pull request.

**Comment by techathena** [comment]
okay :)

**Comment by chivay** [comment]
Looks good :) In future, please keep your branch rebased on top of current master. Otherwise reviewing the changes is nontrivial (GitHub gets confused).

**Comment by techathena** [comment]
yes , I will take care .
Thanks :)

**Pull request merged**
