### PR TITLE
add timeout option for postinstall

### PR DESCRIPTION
**Pull request by malwarefrank**
Add a timeout argument for postinstall.

I had to increase the timeout on my system.  Others may run into this too.

### CODE REVIEW

**Comment by icedevml** [comment]
Hello,

these commands should generally execute within 1-2 seconds, If it took much longer, there is certainly something wrong. Could you describe in which situation you've ran into these timeouts? What is the hardware configuration of the machine you are running DRAKVUF Sandbox and what Windows version are you installing?

**Comment by malwarefrank** [comment]
I saw the VBConf presentation and want to try out DRAKVUF Sandbox.  I have an old Intel i7 laptop with 32G RAM.  I have a fresh install of Ubuntu Focal.  I followed the [Basic Installation directions](https://drakvuf-sandbox.readthedocs.io/en/latest/usage/getting_started.html).  I am using a Windows 10 1703 64-bit iso.

**Comment by icedevml** [comment]
@malwarefrank How long does `draksetup postinstall` take for your setup? Does the sandbox work afterwards?

**Comment by malwarefrank** [comment]
The postinstall command takes approximately 5 minutes.  But even after that, the sandbox is not working.  I am still troubleshooting it.

**Comment by icedevml** [comment]
Thus, I'm afraid this PR doesn't solve the problem.

Please be aware that 1703 is a really old version and Windows 10 support is generally experimental. The best-supported version for DRAKVUF Sandbox is Windows 7 x64, you shouldn't have any problems if you try this.

I'm closing this for now, but thanks for trying to solve a bug.

**Pull request closed without merging**
