### PR TITLE
[DRAFT] [CI] trying something

### PR DESCRIPTION
**Pull request by manorit2001**

### CODE REVIEW

**Comment by manorit2001** [comment]
@chivay if CI requires some approval from your side on `.drone.yml`, can you please pass it?

I was basically trying to skip unnecessary jobs, and trying if it will work this way

**Comment by chivay** [comment]
Hmm, no. the job crashed https://drone.icedev.pl/CERT-Polska/drakvuf-sandbox/2137

**Comment by manorit2001** [comment]
> Hmm, no. the job crashed https://drone.icedev.pl/CERT-Polska/drakvuf-sandbox/2137

Oh :/

**Comment by chivay** [comment]
But I don't think that this change is a good idea. It may break a few things including E2E tests

**Comment by manorit2001** [comment]
> But I don't think that this change is a good idea. It may break a few things including E2E tests

Umm, E2E doesn't depend on these 2 right?

**Comment by manorit2001** [comment]
Ah, this one's gonna be hard to debug for me. Github is not showing the links which are crashing. So.. I'll pass this ig

Thanks for the info!

**Pull request closed without merging**
