### PR TITLE
Hotfix misconfigured click

### LINKED ISSUE #240: Probably misconfigured click
This bug was reported by @mkilijanek via slack.
```
root@drakvuf-w7:/tank/ISO# draksetup install Windows7x64.iso --storage-backend zfs --zfs-tank-name tank/vms
[2020-09-23 10:56:06,854][INFO] Ensuring that drakrun@* services are stopped...
[2020-09-23 10:56:06,899][INFO] Performing installation...
[2020-09-23 10:56:18,560][INFO] Checking xen-detect...
Running in PV context on Xen V4.14.
[2020-09-23 10:56:18,584][INFO] Testing if xl tool is sane...
Traceback (most recent call last):
  File "/usr/bin/draksetup", line 5, in <module>
    ds.main()
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 169, in install
    generate_vm_conf(install_info, 0)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 384, in generate_vm_conf
    storage_backend = get_storage_backend(install_info)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/storage.py", line 265, in get_storage_backend
    return REGISTERED_BACKENDS[install_info.storage_backend](install_info)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/storage.py", line 66, in __init__
    raise RuntimeError("zfs_tank_name is missing from InstallInfo")
RuntimeError: zfs_tank_name is missing from InstallInfo
```

In 0.9.0 we replaced Argparse with click which is much more prone to errors (such as this one) and impossible to test via mypy. I've created a PR which fixes this issue, but I'm afraid more will araise in the future. As a long term solution I again ask @icedevml and @chivay to remove `click` as I **still** consider it harmful to the project and go back to `argparse`.

### PR DESCRIPTION
**Pull request by BonusPlay**
should fix #240
**PLEASE TEST BEFORE APPROVING/MERGE** as it was not tested yet.

### CODE REVIEW

**Comment by icedevml** [comment]
Testing this today

**Review by icedevml — CHANGES_REQUESTED** [review]
unfortunately doesn't seem to help

I get exactly the same error message as in #240

**Comment by BonusPlay** [comment]
Ok, I'll look into it in ~1h.

**Comment by BonusPlay** [comment]
@icedevml tested locally and now it works, we make a bugfix release :)

**Review by icedevml — APPROVED** [review]
LGTM

**Pull request merged**
