### PR TITLE
Store drakrun/drak-postprocess logs in Minio

### PR DESCRIPTION
**Pull request by chivay**
This patch adds drakrun and drak-postprocess logs for each analysis
in Minio. This allows for easier debugging as the logs can be viewed
directly in browser instead of SSHing into the server.

Currently, we have no shared code between drakrun and drakcore so some
of the changes are duplicated.

### CODE REVIEW

**Review by icedevml — COMMENTED** [review]
most probably this should be upstreamed to karton (which is in fact common code between drakrun and drakcore), it looks pretty much like a feature for a karton framework

**Comment by chivay** [comment]
:+1: seems reasonable. I'll look into it

**Comment by icedevml** [comment]
related #242

**Review by icedevml — APPROVED** [review]
LGTM for now, a ticket was created to refactor it later

**Pull request merged**
