### PR TITLE
Send a task after postprocessing

### LINKED ISSUE #371: Send new task after postprocessing
It's not possible to listen for an end of postprocessing. Send a task when it has finished doing things.

### PR DESCRIPTION
**Pull request by chivay**
This should resolve #371 
Currently there's no way to easily wait until postprocessing artifacts are generated. 
Fix this by sending a new task after finishing all postprocessing steps.

### CODE REVIEW

**Review by icedevml — COMMENTED** [review]
Task is not derived from the original one, I think it should be. Otherwise it creates a separate karton task tree

**Comment by chivay** [comment]
It will be attachted. Docs state that (about  `send_task`):
>Sends a task to the unrouted task queue. Takes care of logging. Given task will be child of task we are currently handling (if such exists).

**Review by icedevml — APPROVED** [review]
ack

**Comment by icedevml** [comment]
please create dev-build after merging

**Comment by chivay** [comment]
ACK, give me a moment to test it.

**Pull request merged**
