### PR TITLE
Hitting a bullseye - Bump DRAKVUF

### PR DESCRIPTION
**Pull request by chivay**

### CODE REVIEW

**Review by BonusPlay — APPROVED** [review]

**Comment by BonusPlay** [comment]
Seems like https://github.com/tklengyel/drakvuf/pull/1387 changed logging format? Needs investigation.

**Comment by chivay** [comment]
From initial testing:
```
# cat /var/log/xen/qemu-dm-vm-0.log
qemu-system-i386: warning: '-soundhw hda' is deprecated, please use '-device intel-hda -device hda-duplex' instead
qemu-system-i386: -vnc 0.0.0.0:0,password=on,to=99: Cipher backend does not support DES algorithm
```

**Comment by chivay** [comment]
Probably relevant: [Cipher backend does not support DES algorithm](https://bugs.gentoo.org/832494)

**Comment by chivay** [comment]
Created a pull request in upstream: https://github.com/tklengyel/drakvuf/pull/1396

**Comment by BonusPlay** [comment]
CI seems weird :thinking:

**Comment by chivay** [comment]
Weird, the deb file was built correctly :thinking: 
https://minio.drakvuf.cert.pl/debs/drakvuf-bundle-fecea59a2a4a1361a9289bb2e111a3d35e54065a.deb

**Pull request merged**
