### PR TITLE
dh-virtualenv: pin to specific Python version instead of using the default one

### LINKED ISSUE #64: Xubuntu 18.04 compatibility: missing dataclasses package
In Xubuntu 18.04, there is a problem with drakcore UI caused by lack of `dataclasses` module (builtin since Python 3.7, but Xubuntu has Python 3.6).

This is not on our list of officially supported systems but if this is an only issue and it is related just to the compatibility with Python 3.6 then we could probably study the topic.

```
Apr 28 16:52:46 ubuntu uwsgi[3909]: Traceback (most recent call last): Apr 28 16:52:46 ubuntu uwsgi[3909]:   File "/opt/venvs/drakcore/lib/python3.6/site-packages/drakcore/app.py", line 16, in <module> Apr 28 16:52:46 ubuntu uwsgi[3909]:     from drakcore.pstree import generate_process_tree Apr 28 16:52:46 ubuntu uwsgi[3909]:   File "/opt/venvs/drakcore/lib/python3.6/site-packages/drakcore/pstree.py", line 2, in <module> Apr 28 16:52:46 ubuntu uwsgi[3909]:     from dataclasses import dataclass, field Apr 28 16:52:46 ubuntu uwsgi[3909]: ModuleNotFoundError: No module named 'dataclasses'
```

### LINKED ISSUE #100: Internal Server Error when visiting localhost:6300
**Describe the bug**

After completing the necessary steps to complete the installation of the sandbox, I tried to go to http://localhost:6300. Instead of the the web UI, I was greeted with an internal server error. 

**How to reproduce**

1. Install sandbox as instructed
2. Execute `sudo draksetup postinstall`
3. Visit localhost:6300

**Output of the [status checking commands](https://github.com/CERT-Polska/drakvuf-sandbox#checking-service-status)**

### systemctl status drak-web.service
```
drak-web.service - drak-web service
   Loaded: loaded (/etc/systemd/system/drak-web.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2020-05-09 23:49:53 PDT; 10min ago
 Main PID: 783 (uwsgi)
    Tasks: 6 (limit: 2207)
   CGroup: /system.slice/drak-web.service
           ├─ 783 /opt/venvs/drakcore/bin/uwsgi --ini /etc/drakcore/uwsgi.ini
           ├─1014 /opt/venvs/drakcore/bin/uwsgi --ini /etc/drakcore/uwsgi.ini
           ├─1016 /opt/venvs/drakcore/bin/uwsgi --ini /etc/drakcore/uwsgi.ini
           ├─1018 /opt/venvs/drakcore/bin/uwsgi --ini /etc/drakcore/uwsgi.ini
           ├─1029 /opt/venvs/drakcore/bin/uwsgi --ini /etc/drakcore/uwsgi.ini
           └─1030 /opt/venvs/drakcore/bin/uwsgi --ini /etc/drakcore/uwsgi.ini

May 09 23:49:59 ubuntu uwsgi[783]: *** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
May 09 23:49:59 ubuntu uwsgi[783]: *** uWSGI is running in multiple interpreter mode ***
May 09 23:49:59 ubuntu uwsgi[783]: spawned uWSGI master process (pid: 783)
May 09 23:49:59 ubuntu uwsgi[783]: spawned uWSGI worker 1 (pid: 1014, cores: 1)
May 09 23:49:59 ubuntu uwsgi[783]: spawned uWSGI worker 2 (pid: 1016, cores: 1)
May 09 23:50:00 ubuntu uwsgi[783]: spawned uWSGI worker 3 (pid: 1018, cores: 1)
May 09 23:50:00 ubuntu uwsgi[783]: spawned uWSGI worker 4 (pid: 1029, cores: 1)
May 09 23:50:00 ubuntu uwsgi[783]: spawned uWSGI http 1 (pid: 1030)
May 09 23:52:48 ubuntu uwsgi[783]: --- no python application found, check your startup logs for errors ---
May 09 23:52:48 ubuntu uwsgi[783]: [pid: 1014|app: -1|req: -1/1] 127.0.0.1 () {36 vars in 563 bytes} [Sat May  9 23:52:48 2020] GET / => generated 21 bytes in 2 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
```

### sudo systemctl status drakrun@1.service
```
drakrun@1.service - drakrun service
   Loaded: loaded (/etc/systemd/system/drakrun@.service; indirect; vendor preset: enabled)
   Active: active (running) since Sat 2020-05-09 23:50:07 PDT; 16min ago
 Main PID: 1334 (drakrun)
    Tasks: 1 (limit: 2207)
   CGroup: /system.slice/system-drakrun.slice/drakrun@1.service
           └─1334 /opt/venvs/drakrun/bin/python /opt/venvs/drakrun/bin/drakrun 1

May 09 23:50:07 ubuntu systemd[1]: Started drakrun service.
May 09 23:52:07 ubuntu drakrun[1334]: iptables: Bad rule (does a matching rule exist in that chain?).
May 09 23:52:07 ubuntu drakrun[1334]: iptables: Bad rule (does a matching rule exist in that chain?).
May 09 23:52:07 ubuntu drakrun[1334]: [2020-05-09 23:52:07,174][INFO] Service karton.drakrun-prod started
May 09 23:52:07 ubuntu drakrun[1334]: [2020-05-09 23:52:07,187][INFO] Service binds created.
May 09 23:52:07 ubuntu drakrun[1334]: [2020-05-09 23:52:07,195][INFO] Binding on: {'type': 'sample', 'stage': 'recognized', 'platform': 'win32'}
May 09 23:52:07 ubuntu drakrun[1334]: [2020-05-09 23:52:07,198][INFO] Binding on: {'type': 'sample', 'stage': 'recognized', 'platform': 'win64'}
```

### tree /var/lib/drakcore
```
.
└── minio
    ├── drakrun
    ├── karton2
    └── .minio.sys
        ├── backend-encrypted
        ├── buckets
        │   ├── .bloomcycle.bin
        │   ├── .minio.sys
        │   │   └── buckets
        │   │       ├── .bloomcycle.bin
        │   │       │   └── fs.json
        │   │       ├── .usage-cache.bin
        │   │       │   └── fs.json
        │   │       └── .usage.json
        │   │           └── fs.json
        │   ├── .tracker.bin
        │   ├── .usage-cache.bin
        │   └── .usage.json
        ├── config
        │   ├── config.json
        │   └── iam
        │       └── format.json
        ├── format.json
        ├── multipart
        └── tmp
            ├── 64f8397f-8834-4223-83c1-336df8a504ef
            ├── 72d1d724-222f-44a6-810c-a24e2c742133
            ├── b7219802-97ef-4e4a-b647-55979848954f
            └── f8c8d0cb-6d09-4a91-bc9b-53fbebf64459

18 directories, 11 files
```

### LINKED ISSUE #102: Avoid running on Python 3.6 or ensure compatibility with it
related #100

sometimes Ubuntu 18.04 has Python 3.6 as default interpreter but we don't really support such situation

### PR DESCRIPTION
**Pull request by icedevml**
resolve #64
resolve #102
resolve #100

### CODE REVIEW

**Comment by BonusPlay** [comment]
LGTM, but probably @chivay should review it

**Comment by icedevml** [comment]
@chivay

**Comment by chivay** [comment]
I'm not a fan of duplicatiing the scripts in both directories, however I can't see any better alternative :thinking:

**Comment by icedevml** [comment]
We always have a chance to improve it later ;)

**Pull request merged**
