### PR TITLE
Adding a client library and CLI utility for interacting with DRAKVUF Sandbox

### PR DESCRIPTION
**Pull request by cmcginls**
This PR supplies a new utility under the `examples/` directory called `sandboxapi`. 
- `client.py` provides a client class for interacting with the Sandbox programmatically
- `cli.py` provides a CLI wrapper called `sandboxcli` for easy interaction with the API.

### CODE REVIEW

**Review by icedevml — COMMENTED** [review]
👍

**Comment by icedevml** [comment]
Hello, thanks for contributing to DRAKVUF Sandbox. This PR will be soon reviewed by one of the maintainers.

**Review by chivay — COMMENTED** [review]
Hi!
First of all, thank you for your PR :) It's awesome to see contributions from external collaborators.

To me, Python client package seems like a very useful thing (we already have a poor man's implementation in `test/utils.py`). However, creating such a library defines a public interface so we should be careful in what and how we want to expose.

Apart from my other comments, I'd also move the package out of the `examples` directory, as this should be a important component of the system.

I guess that the other guys will also have something to add. I could've missed something :thinking:

**Comment by chivay** [comment]
@cmcginls could you rebase onto current master (3428a80) before adding the fixes? It should fix the issue with the CI server not detecting and testing your PR. Thanks!

**Comment by icedevml** [comment]
@cmcginls Hey. We would like to hear from you :) What is your view on the review comments posted above? Do you agree with the review and are you still going to work on this PR?

**Comment by icedevml** [comment]
Closing for inactivity. Feel free to reopen if you want to continue with this.

**Pull request closed without merging**
