### PR TITLE
bump drakvuf to 1.0

### PR DESCRIPTION
**Pull request by BonusPlay**

### CODE REVIEW

**Comment by chivay** [comment]
At least this patch should also be reapplied https://github.com/CERT-Polska/drakvuf/commit/d3a3ac389d6144b1de7794b29f49db33dfcf70bc

**Comment by BonusPlay** [comment]
Good catch.

**Comment by chivay** [comment]
@BonusPlay dll_discovered event was merged. We can bump the submodule

**Review by chivay — APPROVED** [review]
:shipi

**Pull request merged**
